
- name: "type:bug"
  color: "d73a4a"
  description: "Something is broken"
- name: "type:feature"
  color: "a2eeef"
  description: "New feature request"
- name: "type:chore"
  color: "fbca04"
  description: "Maintenance and chores"
- name: "priority:high"
  color: "b60205"
  description: "Critical path"
- name: "priority:low"
  color: "c2e0c6"
  description: "Nice to have"
